### PR TITLE
Bits refactor

### PR DESCRIPTION
**Pull request by da-steve101**
This pr deprecates declaring a UInt with Bits
Changing to return Bits will probably break things so deprecate then change to return Bits down the track
Also deprecated DC in Bool and UInt in favour of BitPat
Rest is fixing deprecation warnings

### CODE REVIEW

**Comment by da-steve101** [comment]
Currently not passing tests. Can't work out why as only appears to be cosmetic changes

**Comment by da-steve101** [comment]
At a bit of a loss with this one. It only happens on the last commit in which i add a few unused functions.
As far as i can tell it occurs on the instantiation of a test module, so it isn't a emulator memory error.
The trace stems from calcElements in Bundle.scala
I have tried increasing the stack and heap size which lead to no visable progress in the tests (at least after 10 minutes) but did not have the StackOverflowError.
Anything obvious that i am missing?

**Comment by ucbjrl** [comment]
Bundle needs to know the Chisel methods that may be invoked on Bundle instances so it can avoid invoking them when creating the sequence of user-defined elements. Add "asBits" and "asUInt" to the list of Bundle keywords.

**Comment by da-steve101** [comment]
Ah yes, that was it! What do you think of asBits and asUInt?
It won't cause clashes with toBits or toUInt (which is overridden). Do we need asBits though?

**Comment by ucbjrl** [comment]
I don't think we need asBits(). I'm also skeptical of Node.asUInt(). We currently have Bits.toUInt(). I'm leery  of introducing more conversion methods into the Node type.

**Comment by da-steve101** [comment]
I think toBits is useful to get the raw bits of a node for manipulation. I agree that asBits() may not be necessary and i'll remove it.
The only issue i have with the toBits is that the name suggests it returns Bits rather than UInt. The suggested change is essentially renaming toBits -> asUInt

**Comment by da-steve101** [comment]
Not passing at the moment.
Think this is low priority anyway.

**Pull request closed without merging**
