### PR TITLE
Right shift fix

### PR DESCRIPTION
**Pull request by da-steve101**
Bug in emulator, right shift not computed properly for numbers over 64 bits long

Added fix and a testSuite

### CODE REVIEW

**Comment by ucbjrl** [comment]
This currently causes failures in reference-chip. We're investigating.

**Comment by ucbjrl** [comment]
The rsh changes to Cpp.scala fail the supplied tests, while current code passes. I've integrated the tests (with minor changes to support Chisel's testerSeed). If you believe current code is incorrect, please update this pr with a test that demonstrates the failure (and an updated fix).

**Comment by da-steve101** [comment]
Hi,

Sorry I should have added the specific case to the test. have now in RshExt which is failing
There appear to be bugs in mine too which i need to fix and haven't yet

**Comment by da-steve101** [comment]
Hi,

I think a better method of doing this is to use the function defined in emulator.h
Its a lot more readable. Let me know what you think

Stephen

**Comment by da-steve101** [comment]
should i close this as is in the branch pr460?
Also i think that the other bit operations should be done this way. Do you agree?
If so ill patch it.

**Comment by ucbjrl** [comment]
Let�s keep it open. I haven�t finished the fixes in pr460 - I don�t have references to a multi-word literals sorted out. I�m hoping to have it done tomorrow.

I�m with you on moving as much complexity as possible into the individual backend implementations, and keeping the Scala code simple, assuming this doesn�t introduce performance issues.

Let�s get input from the rest of the team before proceeding.

**Pull request merged**
