### PR TITLE
Issue deprecation warning on startup.

### PR DESCRIPTION
**Pull request by ucbjrl**

### CODE REVIEW

**Review by edwardcwang — APPROVED** [review]

**Comment by ducky64** [comment]
Does it make sense to print the error at the end of elaboration? Printing it at the start could just mean that it immediately gets pushed off the screen by a wall of text generated during elaboration?

**Review by ducky64 — APPROVED** [review]
Haven't run it (I hope someone has and confirmed that the error messages do indeed print?) but the code looks sane.

**Comment by ducky64** [comment]
Yeah that definitely looks good.

Appears to both print at the end of elaborate
```
CppBackend: createCppFile BitPatSuite_BitPatBoolModule_1.cpp
[[35minfo[0m] [0.521] g++ -c -o test-outputs/BitPatSuite_BitPatBoolModule_1-emulator.o  -I../ -I/csrc/  test-outputs/BitPatSuite_BitPatBoolModule_1-emulator.cpp RET 0
[[35minfo[0m] [0.912] g++ -c -o test-outputs/BitPatSuite_BitPatBoolModule_1.o  -I../ -I/csrc/  test-outputs/BitPatSuite_BitPatBoolModule_1.cpp RET 0
[[35minfo[0m] [0.978] g++   -o test-outputs/BitPatSuite_BitPatBoolModule_1 test-outputs/BitPatSuite_BitPatBoolModule_1.o test-outputs/BitPatSuite_BitPatBoolModule_1-emulator.o RET 0
[[33mwarn[0m]: Chisel2 is deprecated. Please use Chisel3: https://github.com/freechipsproject/chisel3
```
and test
```
STEP 1 -> 7
  EXPECT BitPatSuite_BitPatModule_1.io_out -> 0x0 == 0x0 PASS
  POKE BitPatSuite_BitPatModule_1.io_in <- 0x7
STEP 1 -> 8
  EXPECT BitPatSuite_BitPatModule_1.io_out -> 0x1 == 0x1 PASS
RAN 8 CYCLES PASSED
[[33mwarn[0m]: Chisel2 is deprecated. Please use Chisel3: https://github.com/freechipsproject/chisel3
```

**Comment by ucbjrl** [comment]
Right. We could easily suppress the printing at the end of the test run,
but the argument you raised earlier (the warning may scroll off the screen
given sufficient output) would apply here as well. Suppressing the warning
after elaboration iff we know testing will follow seemed an unwarranted
complication: since we want to discourage usage, erring on the side of too
many warnings seems quite appropriate.

**Comment by ducky64** [comment]
I don't think suppression is a good idea, I posted the two examples there for those who do not have access to the build outputs.

**Comment by ucbjrl** [comment]
We're in violent agreement.

**Pull request merged**
