### PR TITLE
Dump clock signal in VCD waveform dumps

### PR DESCRIPTION
**Pull request by jbush001**
I find it disorienting to not be able to see the clock in VCD waveforms dumped from the C++ simulator. I've added support for dumping this signal, which is named 'clk' and appears in every module. I reserve the first VCD signal identifier '!' for it, and emit a few statements to simulate toggling it at the top of the generated c++ dump() method.

I've updated the unit tests for the new formula and run them to ensure no regressions. I tested the output from my own design in GTKWave to ensure the clock edges lined up and the waveforms made sense.

### CODE REVIEW

**Comment by jbush001** [comment]
I'm pretty sure this won't do the right thing with multiple clock domains.  It makes the main 'clk' transition any time dump is called. Looking at genClockMethod in Cpp.scala, it appears that the period of all clocks is known. If this is the case, dump could walk through the clocks, look at the current timestamp and determine what the state of all clocks should be (and also dump them with their proper names).

**Comment by jbush001** [comment]
I've updated the pull request to support multiple clock domains.

**Comment by donggyukim** [comment]
Did you test this with MultiClockDomain in Chisel tutorial? I got an error when I converted its vcd to vpd.

**Comment by jbush001** [comment]
I did 'make test' at the top level and ensured there were no failures.  I also created my own project with multiple clock domains.  Are you using VCS tools to convert to the VPD format?  What error is it giving you?

**Comment by donggyukim** [comment]
I got this:
  A fatal error occurred at line 193:
  Error: Time parsed (0) is less then the previous time parsed (2).
                  Closing VCD+ file with only data up to this point in the
  dump file..

I think timestamps from the emulators may be wrong.

**Comment by jbush001** [comment]
Okay, that's helpful. I'll take a look.

**Comment by donggyukim** [comment]
I also fix this problem in #469, by assigning objects to clock signals.

**Comment by jbush001** [comment]
I've updated the branch with two fixes:
- Handle arbitrary clock waveform phase
- Fix a bug where timestamps could be out-of-order in the VCD file. This was due to how I was calculating the next event time. Apparently GtkWave was more tolerant of this. I reproduced this in my test configuration and fixed it there. I also ran the MultiClockDomain test from https://github.com/ucb-bar/chisel-tutorial/blob/master/examples/MultiClockDomain.scala. I manually inspected the VCD file and do not see timestamps running backward (The clock waveforms still look messed up because of issue #467).

It seems like I could make a unit test that validates the .VCD waveform once issue #467 is addressed. It could use assertFile and have a model .VCD checked into the resources directory.

**Comment by jbush001** [comment]
Added unit test for VCD output

**Comment by jbush001** [comment]
I think your change de14ec833 obviates the need for this and is cleaner. Closing.

**Comment by jbush001** [comment]
...which you said in your previous comment that I missed earlier. :)

**Pull request closed without merging**
